[pytest]
asyncio_mode = auto
addopts = -v --html=report.html --self-contained-html --cov-report=html:htmlcov
testpaths = tests
python_files = test_*.py *_test.py *_postman.py
env_files =
    .env.dev
